# @package trainer
_target_: lightning.pytorch.trainer.Trainer

# Training configuration
max_epochs: 15
accelerator: "auto"
devices: "auto"
precision: "16-mixed"

# Performance optimizations
accumulate_grad_batches: 1
gradient_clip_val: null
gradient_clip_algorithm: "norm"

# Validation and testing
check_val_every_n_epoch: 1
val_check_interval: 1.0
num_sanity_val_steps: 2

# Logging and progress
enable_progress_bar: true
enable_model_summary: true
log_every_n_steps: 50

# Reproducibility
deterministic: false
benchmark: true

# Other settings
enable_checkpointing: true
