# Base configuration for banana ripeness classification
defaults:
  - model: resnet50
  - data: default
  - trainer: default
  - logger: wandb
  - callbacks: default
  - experiment: null
  - _self_

# Experiment metadata (ML naming conventions)
experiment:
  name: "banana-ripeness-classifier-unknowns"  # Base experiment name
  version: null  # Will auto-generate: v2025.10.01
  tag: null      # Optional: "baseline", "improved", etc.
  notes: "Banana ripeness classification using deep learning"
  tags:          # Additional tags for organization
    - "computer-vision"
    - "food-classification"
    - "pytorch-lightning"

# Hydra configuration - aligned with ML naming system
hydra:
  run:
    dir: ../outputs/hydra/${now:%Y-%m-%d_%H-%M-%S}  # Redirect to project root
  sweep:
    dir: ../outputs/sweeps/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra:job.num}
  job:
    chdir: false  # Don't change working directory
  output_subdir: .hydra  # Keep .hydra folder in run dir
