# @package model
_target_: src.model.MobileNetClassifier

# Model architecture
model_name: "mobilenet_v3_small"
pretrained: true
freeze_backbone: false
dropout_rate: 0.3

# Training parameters
num_classes: 4
learning_rate: 1e-3
weight_decay: 1e-4
scheduler: "cosine"

# Logging
log_wandb: true
