# @package _global_

# YOLO-based model configuration
model:
  _target_: src.model.YOLOClassifier
  model_name: "yolov8n"  # yolov8n, yolov8s, yolov8m, yolov8l, yolov8x
  pretrained: true
  confidence_threshold: 0.5
  num_classes: 4
  learning_rate: 1e-3
  weight_decay: 1e-4
  scheduler: "cosine"

# Model-specific training settings
trainer:
  max_epochs: 20
  accelerator: "auto"
  devices: "auto"
  precision: "16-mixed"

# Data settings optimized for YOLO
data:
  batch_size: 16  # Smaller batch size for YOLO due to memory usage
  num_workers: 4
  image_size: 640  # Standard YOLO input size
