# @package callbacks.accuracy_logger
_target_: src.callbacks.AccuracyLoggerCallback

# Logging behavior
log_on_step: false
log_on_epoch: true
prog_bar: true

# Per-class metrics
log_per_class: false  # Set to true for detailed per-class accuracy

# Model configuration
num_classes: 4
