# @package callbacks.model_checkpoint
_target_: lightning.pytorch.callbacks.ModelCheckpoint

# Monitoring
monitor: "val/acc"
mode: "max"
save_top_k: 3
save_last: true
save_weights_only: false

# File naming
filename: "epoch_{epoch:02d}_val_acc_{val/acc:.3f}"
auto_insert_metric_name: false

# Directory
dirpath: null  # Will be set by trainer_helper

# Other settings
verbose: true
save_on_train_epoch_end: false
