# @package callbacks.precision_logger
_target_: src.callbacks.PrecisionLoggerCallback

# Logging behavior
log_on_step: false
log_on_epoch: true
prog_bar: false  # Not shown in progress bar by default

# Per-class metrics
log_per_class: false  # Set to true for detailed per-class precision

# Model configuration
num_classes: 4
